### ISSUE TITLE
Feature Request: allow to view binary data as UTF-8

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#128]
Binary data, e.g. the contents of files, are now shown Base64 encoded in Ladybug. This is confusing, as it looks like the data is Base64 encoded, which it is (in most cases) not. It would be nice if the user could select runtime to view the data as UTF-8 or hexadecimal

**Comment by jacodg** [comment]
Implemented with https://github.com/ibissource/ibis-ladybug/commit/f6fcacdb8ca881a83a13882c748cde14b3f7f9d5
