### ISSUE TITLE
Ladybug is not setting (any) mimetypes.

### ISSUE THREAD

**Issue by nielsm5** [ibissource/ibis-ladybug#154]
After enabling `X-Content-Type-Options` on the framework the Ladybug no longer works and returns the following error in the browser console:
```
Refused to execute script from 'http://localhost/iaf-test/testtool?serviceId=Echo.ClientEngine' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

After looking into the requests they all seem to have Content-Type: text/plain.

**Comment by jacodg** [comment]
https://github.com/ibissource/ibis-echo2/commit/65b296dc898af3b9676b8a9e5a14b36fcd2a95e8
https://github.com/ibissource/ibis-ladybug/commit/89eb368da955a3650f950b1fc437a44fa00efadd
https://github.com/ibissource/iaf/pull/3613/
