### ISSUE TITLE
'Synchronize compare trees' in proof of migration should sync on checkpoint_nr

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#174]
The button 'Synchronize compare trees' synchronize on line number in the trees. This fails to find the right match if orphans exist higher up in the tree. Better results would be achieved by synchronizing on checkpoint_nr

**Comment by celmoussaoui** [comment]
@gvanbrakel Can you please elaborate, as the synchronization is done through the entire path instead of the mentioned line numbers in the tree.

**Comment by celmoussaoui** [comment]
This will be further handled in the following issue https://github.com/ibissource/ladybug-frontend/issues/288

**Comment by celmoussaoui** [comment]
This issue has been resolved
