### ISSUE TITLE
Message: Running out of disk space is comming but should not)

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/ibis-ladybug#46]
in the new implementatio of the ladybug used in the ibis4oma we see an error / warning message) that we would not expect

I think the formula that is used is wrong as we still have 4 Gb available

[Running out of disk space (4.776.054.784 bytes left) (reports are not stored while free space is below 10485760000 bytes to prevent corrupt storage files)]

**problem is in this commit**
https://github.com/ibissource/ibis-ladybug/commit/62947a8a903b974a9419150a6235044dd78fbba9

```
// called after openFiles() has been called).
	if (reportsFile.exists()) {
		long freeSpace = reportsFile.getFreeSpace();
		long minimum = maximumFileSize * (maximumBackupIndex + 1) * 10;        **ibistesttool.maxFileSize | 100MB** **maximumBackupIndex?** 
		if (maximumFileSize != -1 && freeSpace < minimum) {
			return "Running out of disk space (" + freeSpace
					+ " bytes left) (reports are not stored while free space is below " + minimum
					+ " bytes to prevent corrupt storage files)";
		}
	}
 
```

**Comment by jacodg** [comment]
This has been fixed with https://github.com/ibissource/ibis-ladybug/commit/d14578878f55cf89dbfcc3ca29379592d356f19b
