### ISSUE TITLE
Ladybug is not showing the whole work flow

### ISSUE THREAD

**Issue by Bibi0803** [ibissource/ibis-ladybug#49]
![Capture](https://user-images.githubusercontent.com/60199670/96977557-87b5b700-151d-11eb-88c7-c5e94984121f.PNG)

When I add "parallel" and "maxChildThreads" attributes to the pipe "ArchiveRDWRecordsetsAndRDWRecords" which is a ForEachChildElementPipe, I don't see the flow of this pipe any more (See above picture), this pipe is executed, the output is correct, but just don't see what is going on. And if I remove those two attributes, the work flow of this pipe appears again as follow: 

![Capture 1](https://user-images.githubusercontent.com/60199670/96978558-c8fa9680-151e-11eb-9863-250c98754cfe.PNG)

**Comment by jacodg** [comment]
This should be fixed with https://github.com/ibissource/iaf/pull/1351
