### ISSUE TITLE
FeatureRequest: facility to cancel announced child threads.

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#62]
Sometimes a child thread is expected and announced, but in the end it was not started, and it is known that it will not be started. In such a case one would like to cancel the announced child thread.
See https://github.com/ibissource/iaf/pull/1606
See IbisDebuggerAdvice.cancelChildTread()

**Comment by jacodg** [comment]
Fixed with https://github.com/ibissource/ibis-ladybug/commit/c29d3213f3fac8d71736c00bb1c080ebbb560d97
