### ISSUE TITLE
IndexOutOfBoundsException when using old console

### ISSUE THREAD

**Issue by nielsm5** [ibissource/ibis-ladybug#63]
Tested with version 2.0.15-20210106.180557. See 
[ladybug-stracktrace.txt](https://github.com/ibissource/ibis-ladybug/files/6241770/ladybug-stracktrace.txt)

**Comment by jacodg** [comment]
I think this is a duplicate of https://github.com/ibissource/ibis-ladybug/issues/60 which has been fixed, can you test/confirm?

**Comment by jacodg** [comment]
Is indeed fixed according to Niels
