### ISSUE TITLE
NullPointerException in TestTool.checkpoint

### ISSUE THREAD

**Issue by nielsm5** [ibissource/ibis-ladybug#79]
After using the latest ladybug version I'm getting occasional NullPointerExceptions.
It happend when running the larva scenarios in IAF-test on one of the /cache/sender scenarios.

[NPE.txt](https://github.com/ibissource/ibis-ladybug/files/7454429/NPE.txt)

**Comment by rvdstel** [comment]
[NullPointerException.txt](https://github.com/ibissource/ibis-ladybug/files/7454458/NullPointerException.txt)
Ook in ibis4titan op testomgeving dezelfde fout, FF! 7.7-20211101.091958.

**Comment by jacodg** [comment]
Should be fixed with https://github.com/ibissource/ibis-ladybug/commit/ac8cecc87681d2957f2d846f22c011e4f1f97404
